### ISSUE TITLE
Missing labels in the flexform

### ISSUE THREAD

**Issue by dmitryd** [passionweb-manuel-schnabel/form-email-contentblocks#1]
EXT version: 1.1.1

When using "Override finisher settings" in the form plugin, labels are missing in the flexform:

![iScreen Shoter - Safari - 230724170950](https://github.com/passionweb-manuel-schnabel/form-email-contentblocks/assets/306133/9c07c4b0-4b3b-4760-b0be-6dda3e4f231f)

**Comment by dmitryd** [comment]
There is no branch for release v11, so I could not make a MR. You can see the fix above or use the attached patch.

[0001-BUGFIX-Fix-1-missing-labels-in-the-flexform.patch](https://github.com/passionweb-manuel-schnabel/form-email-contentblocks/files/12159884/0001-BUGFIX-Fix-1-missing-labels-in-the-flexform.patch)

**Comment by passionweb-manuel-schnabel** [comment]
Hey @dmitryd,

thanks for your issue report.

There is no extra branch for the v11. The v11 version is on the master branch ;-)
Would be great if you just create a pull request there with your changes.

Thanks in advance!

Greetings Manu

**Comment by dmitryd** [comment]
Thanks, did it!

**Comment by passionweb-manuel-schnabel** [comment]
I looked at the changes and everything is fine. 

I merged your PR and also made the fix for v12 because the problem also existed there.

The labels are now displayed correctly with version 1.1.2 (v11) or 2.1.1 (v12).

**Comment by dmitryd** [comment]
Thank you very much!
